// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV6SDm_I7d0rpKAl3TI_UMGKW1MGIY6-k',
    appId: '1:249612008871:web:4aca4f690b97336c120a82',
    messagingSenderId: '249612008871',
    projectId: 'followupapp-66532',
    authDomain: 'followupapp-66532.firebaseapp.com',
    storageBucket: 'followupapp-66532.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4HkEmXLOFDAPUSzGqxWmbwqdTqZ5Siis',
    appId: '1:249612008871:android:5f14e6c5ccbc646d120a82',
    messagingSenderId: '249612008871',
    projectId: 'followupapp-66532',
    storageBucket: 'followupapp-66532.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOIdqw3nrx6VMHDD0h8W-cFd2tKIRABv0',
    appId: '1:249612008871:ios:cb01c82bd7c84fef120a82',
    messagingSenderId: '249612008871',
    projectId: 'followupapp-66532',
    storageBucket: 'followupapp-66532.appspot.com',
    iosBundleId: 'com.example.followUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOIdqw3nrx6VMHDD0h8W-cFd2tKIRABv0',
    appId: '1:249612008871:ios:cb01c82bd7c84fef120a82',
    messagingSenderId: '249612008871',
    projectId: 'followupapp-66532',
    storageBucket: 'followupapp-66532.appspot.com',
    iosBundleId: 'com.example.followUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV6SDm_I7d0rpKAl3TI_UMGKW1MGIY6-k',
    appId: '1:249612008871:web:dc91522a41f65e8c120a82',
    messagingSenderId: '249612008871',
    projectId: 'followupapp-66532',
    authDomain: 'followupapp-66532.firebaseapp.com',
    storageBucket: 'followupapp-66532.appspot.com',
  );
}
